
listoflinuxapp:
  - name: firstlinuxapp    
    os_type: Linux
    sku_name: P1v2
  - name: thirdlinuxapp    
    os_type: Linux
    sku_name: P1v2

secondwindowsapp    
    os_type: Windows
    sku_name: P5mv3
  - name: thirdwindowsapp    
    os_type: Windows
    sku_name: P5mv3
